const test=require('node:test');const assert=require('node:assert/strict');
const {event,reply,mocked,fixtureFeed,withEnv}=require('./helpers.cjs');
const {instantToLocal,eventWindow}=require('@/lib/time');
const G=require('@/lib/connectors/global');const W=require('@/lib/connectors/warnings');const T=require('@/lib/connectors/transport');
const nowEvent=(extra={})=>event({dateTime:instantToLocal(new Date(Date.now()+3600000),'Europe/Lisbon').slice(0,16),...extra});
const active=()=>({start:new Date(Date.now()-60000).toISOString(),end:new Date(Date.now()+6*3600000).toISOString()});

test('TomTom uses documented Orbis endpoint, headers and filters',()=>withEnv({TOMTOM_API_KEY:'TEST_ONLY'},()=>mocked((u,o)=>{assert.equal(u.pathname,'/maps/orbis/traffic/incidents/details');assert.equal(u.searchParams.get('apiVersion'),'2');assert.equal(u.searchParams.get('timeValidity'),'present,future');assert.equal(o.headers.get('TomTom-Api-Key'),'TEST_ONLY');assert.equal(o.headers.get('TomTom-Api-Version'),'2');assert.equal(o.headers.get('Attributes'),'incidents');return reply({incidents:[{geometry:{type:'Point',coordinates:[-9.14,38.72]},properties:{id:'work',iconCategory:'roadWorks',timeValidity:'future',probabilityOfOccurrence:'certain',startTime:'2026-10-10T17:00:00Z',endTime:'2026-10-10T20:00:00Z',events:[{description:'Published roadworks'}]}}]});},async()=>{const r=await T.checkTomTom(event());assert.equal(r.state,'checked');assert.equal(r.data[0].resolutionEligible,true);assert.equal(r.data[0].title,'Roadworks');})));
test('TomTom live accident never becomes a resolvable scheduled conflict',()=>{const r=T.parseTomTom({incidents:[{geometry:{type:'Point',coordinates:[-9.14,38.72]},properties:{id:'accident',iconCategory:'accident',timeValidity:'present',startTime:'2026-10-10T17:00:00Z',endTime:'2026-10-10T20:00:00Z'}}]},event());assert.equal(r.data[0].resolutionEligible,false);assert.equal(r.data[0].timing,'live');});
test('TomTom missing geometry is partial, not silently clear',()=>{assert.equal(T.parseTomTom({incidents:[{properties:{id:'x'}}]},event()).partial,true);});
test('Missing TomTom key makes no outbound call',()=>withEnv({TOMTOM_API_KEY:undefined},()=>mocked(()=>{throw Error('No call allowed');},async calls=>{assert.equal((await T.checkTomTom(event())).state,'not_configured');assert.equal(calls.length,0);})));

test('Transitland queries nearby stops with explicit alert inclusion and API key',()=>withEnv({TRANSITLAND_API_KEY:'TEST_ONLY',APP_USAGE:'noncommercial'},()=>mocked((u,o)=>{assert.equal(u.pathname,'/api/v2/rest/stops');assert.equal(u.searchParams.get('include_alerts'),'true');assert.equal(u.searchParams.get('radius'),'2000');assert.equal(o.headers.get('apikey'),'TEST_ONLY');return reply({stops:[]});},async()=>{const r=await T.checkTransitland(event());assert.equal(r.state,'partial');assert.match(r.message,/trip|bounded/);})));
test('Transitland follows serving route and agency alerts without claiming full coverage',()=>withEnv({TRANSITLAND_API_KEY:'TEST_ONLY',APP_USAGE:'noncommercial'},()=>mocked(u=>{
 if(u.pathname.endsWith('/stops'))return reply({stops:[{stop_name:'Test stop',routes:[{id:1,agency:{id:2}}]}]});
 if(u.pathname.endsWith('/routes/1'))return reply({routes:[{route_long_name:'Test route',alerts:[{id:'route-change',effect:'NO_SERVICE',header_text:[{text:'No service',language:'en'}],active_period:[{start:1791651600,end:1791662400}]}]}]});
 if(u.pathname.endsWith('/agencies/2'))return reply({agencies:[{agency_name:'Test operator',alerts:[]}]});throw Error('Unexpected URL');
},async calls=>{const r=await T.checkTransitland(event());assert.equal(calls.length,3);assert.equal(r.state,'partial');assert.ok(r.data.some(c=>c.title==='No service'));})));

test('Ticketmaster serializes dates without milliseconds and uses geoPoint',()=>withEnv({TICKETMASTER_API_KEY:'TEST_ONLY',APP_USAGE:'noncommercial'},()=>mocked(u=>{assert.equal(u.pathname,'/discovery/v2/events.json');assert.ok(u.searchParams.has('geoPoint'));assert.equal(u.searchParams.has('latlong'),false);assert.match(u.searchParams.get('startEndDateTime'),/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z,\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/);return reply({page:{totalElements:1},_embedded:{events:[{id:'listing',name:'Music night',url:'https://tickets.example.org/event',dates:{start:{dateTime:'2026-10-10T17:30:00Z',localDate:'2026-10-10'}},_embedded:{venues:[{name:'Music venue',location:{latitude:'38.72',longitude:'-9.14'}}]}}]}});},async()=>{const r=await require('@/lib/ticketmaster').checkTicketmaster(event());assert.equal(r.state,'checked');assert.equal(r.data[0].title,'Music night');assert.equal(r.data[0].source,'Ticketmaster');assert.equal(r.data[0].relevance,'context');assert.equal(r.data[0].resolutionEligible,false);})));
test('Commercial Ticketmaster requests are gated without permission',()=>withEnv({APP_USAGE:'commercial',TICKETMASTER_COMMERCIAL_PERMISSION:'false',TICKETMASTER_API_KEY:'TEST_ONLY'},()=>mocked(()=>{throw Error('Forbidden');},async calls=>{assert.equal((await require('@/lib/ticketmaster').checkTicketmaster(event())).state,'disabled');assert.equal(calls.length,0);})));

test('Football uses an exclusive upper date and labels the estimated duration',()=>withEnv({FOOTBALL_DATA_API_KEY:'TEST_ONLY'},()=>mocked((u,o)=>{assert.equal(u.searchParams.get('dateTo'),'2026-10-11');assert.equal(o.headers.get('X-Auth-Token'),'TEST_ONLY');return reply({matches:[{id:1,utcDate:'2026-10-10T17:00:00Z',status:'SCHEDULED',homeTeam:{name:'Benfica',tla:'BEN'},awayTeam:{name:'Porto'},competition:{name:'Example league'}}]});},async()=>{const r=await require('@/lib/football-data').checkFootballData(event({footballTeam:'BEN'}));assert.equal(r.state,'checked');assert.equal(r.data.length,1);assert.match(r.data[0].caveat,/estimated/);})));
test('Football matches any of several selected teams by API id',()=>withEnv({FOOTBALL_DATA_API_KEY:'TEST_ONLY'},()=>mocked(()=>reply({
  matches:[
    {id:10,utcDate:'2026-10-10T17:00:00Z',status:'SCHEDULED',homeTeam:{id:110,name:'Benfica',tla:'BEN'},awayTeam:{id:120,name:'Porto',tla:'POR'},competition:{name:'Primeira Liga'}},
    {id:11,utcDate:'2026-10-10T17:00:00Z',status:'SCHEDULED',homeTeam:{id:130,name:'Sporting CP',tla:'SPO'},awayTeam:{id:140,name:'Braga',tla:'BRA'},competition:{name:'Example league'}},
    {id:12,utcDate:'2026-10-10T17:00:00Z',status:'SCHEDULED',homeTeam:{id:150,name:'Guimaraes',tla:'GUI'},awayTeam:{id:160,name:'Portimonense',tla:'PTM'},competition:{name:'Example league'}}
  ]
}),async()=>{const r=await require('@/lib/football-data').checkFootballData(event({footballTeams:[{id:140,name:'Braga'},{id:110,name:'Benfica'}]}));assert.equal(r.state,'checked');assert.equal(r.data.length,2);assert.ok(r.data.every(c=>c.providerId==='football'));})));
test('Football treats an empty team list as no team selected',async()=>{const r=await require('@/lib/football-data').checkFootballData(event({footballTeams:[]}));assert.equal(r.state,'not_applicable');});
test('API-Football fixtures are checked for selected worldwide teams',()=>withEnv({API_FOOTBALL_KEY:'TEST_AF'},()=>mocked((u,o)=>{assert.equal(u.hostname,'v3.football.api-sports.io');assert.equal(u.pathname,'/fixtures');assert.equal(u.searchParams.get('team'),'77');assert.equal(new Headers(o.headers).get('x-apisports-key'),'TEST_AF');return reply({response:[{fixture:{id:1,date:'2026-10-10T17:00:00Z',status:{short:'NS'}},teams:{home:{name:'Global FC'},away:{name:'Rivals'}},league:{name:'World League'}}]});},async()=>{const r=await require('@/lib/api-football').checkFootballAf(event({footballTeams:[{id:77,name:'Global FC',source:'api-football'}]}));assert.equal(r.state,'checked');assert.equal(r.data.length,1);assert.equal(r.data[0].title,'Global FC vs Rivals');assert.equal(r.data[0].source,'API-Football');})));
test('API-Football cancels fixtures filter out cancelled matches',()=>withEnv({API_FOOTBALL_KEY:'TEST_AF'},()=>mocked(()=>reply({response:[{fixture:{id:2,date:'2026-10-10T17:00:00Z',status:{short:'CANC'}},teams:{home:{name:'A'},away:{name:'B'}},league:{name:'Cup'}}]}),async()=>{const r=await require('@/lib/api-football').checkFootballAf(event({footballTeams:[{id:1,name:'A',source:'api-football'}]}));assert.equal(r.state,'checked');assert.equal(r.data.length,0);})));
test('API-Football reports not connected without credentials and skips football-data check',()=>withEnv({API_FOOTBALL_KEY:undefined},async()=>{const r=await require('@/lib/api-football').checkFootballAf(event({footballTeams:[{id:1,name:'A',source:'api-football'}]}));assert.equal(r.state,'not_configured');const fd=await require('@/lib/football-data').checkFootballData(event({footballTeams:[{id:1,name:'A',source:'api-football'}]}));assert.equal(fd.state,'not_applicable');}));
test('API-Football team search maps country detail',()=>withEnv({API_FOOTBALL_KEY:'TEST_AF'},()=>mocked((u,o)=>{assert.equal(u.pathname,'/teams');assert.equal(u.searchParams.get('search'),'global');assert.equal(new Headers(o.headers).get('x-apisports-key'),'TEST_AF');return reply({response:[{team:{id:5,name:'Global FC',country:'Brazil'}}]});},async()=>{const r=await require('@/lib/api-football').searchApiFootballTeams('global');assert.deepEqual(r,[{id:5,name:'Global FC',detail:'Brazil · API-Football'}]);})));
test('TVmaze checks adjacent broadcast dates for an exact programme ID',()=>mocked(u=>{assert.equal(u.pathname,'/shows/1/episodesbydate');return reply(u.searchParams.get('date')==='2026-10-10'?[{id:5,name:'Episode',season:1,number:2,airstamp:'2026-10-10T17:30:00Z',runtime:30,url:'https://www.tvmaze.com/episodes/5'}]:[]);},async calls=>{const r=await require('@/lib/tvmaze').checkTVmaze(event({programmeId:1,programmeName:'Exact show'}));assert.equal(calls.length,3);assert.equal(r.data.length,1);assert.equal(r.data[0].endsAt,'2026-10-10T18:00:00.000Z');}));
test('TVmaze does not fabricate an unknown episode duration',()=>mocked(u=>reply(u.searchParams.get('date')==='2026-10-10'?[{id:5,name:'Episode',season:1,number:2,airstamp:'2026-10-10T17:30:00Z'}]:[]),async()=>{const r=await require('@/lib/tvmaze').checkTVmaze(event({programmeId:1,programmeName:'Show'}));assert.equal(r.state,'partial');assert.equal(r.data.length,0);}));

test('MET rounds coordinates, identifies itself, and interprets forecast period totals',()=>withEnv({MET_USER_AGENT:'BadTiming-Test/3.0 contact: test@example.org'},()=>mocked((u,o)=>{assert.match(u.searchParams.get('lat'),/^38\.7200$/);assert.equal(o.headers.get('User-Agent'),'BadTiming-Test/3.0 contact: test@example.org');return reply({properties:{timeseries:[17,18,19].map(hour=>({time:`2026-10-10T${hour}:00:00Z`,data:{instant:{details:{air_temperature:18,wind_speed:3}},next_1_hours:{details:{precipitation_amount:1}}}}))}});},async()=>{const r=await require('@/lib/weather').checkWeather(event());assert.equal(r.state,'checked');assert.equal(r.data[0].policyKey,'weather:rain');assert.match(r.data[0].description,/1-hour/);})));
test('MET dates outside its returned horizon are not checked clear',()=>withEnv({MET_USER_AGENT:'Test contact test@example.org'},()=>mocked(()=>reply({properties:{timeseries:[{time:'2026-10-09T00:00:00Z',data:{}}]}}),async()=>{assert.equal((await require('@/lib/weather').checkWeather(event())).state,'out_of_range');})));
test('MET six-hour values are not labelled as one-hour rainfall',()=>{const r=require('@/lib/weather').parseWeather({properties:{timeseries:[12,18].map(hour=>({time:`2026-10-10T${hour}:00:00Z`,data:{instant:{details:{air_temperature:18,wind_speed:3}},next_6_hours:{details:{precipitation_amount:6}}}}))}},event({durationMinutes:30}));assert.equal(r.partial,true);assert.match(r.data[0].description,/6-hour/);assert.equal(r.data[0].resolutionEligible,false);});

test('Sunrise-Sunset v2 range responses find the actual night interval',()=>mocked(u=>{assert.equal(u.pathname,'/v2');assert.equal(u.searchParams.get('date_start'),'2026-10-10');assert.equal(u.searchParams.get('date_end'),'2026-10-11');return reply({days:[{date:'2026-10-10',sun_status:'normal',sunrise:'2026-10-10T07:00:00+01:00',sunset:'2026-10-10T18:30:00+01:00'}]});},async()=>{const r=await require('@/lib/daylight').checkDaylight(event());assert.equal(r.state,'checked');assert.equal(r.data.length,1);assert.equal(r.data[0].policyKey,'daylight:darkness');}));
test('Polar daylight is not accidentally parsed as missing solar data',()=>mocked(()=>reply({days:[{date:'2026-10-10',sun_status:'midnight_sun',sunrise:null,sunset:null}]}),async()=>{const r=await require('@/lib/daylight').checkDaylight(event());assert.equal(r.state,'checked');assert.equal(r.data.length,0);}));

test('UK calendar honours the selected division and year coverage',()=>mocked(()=>reply({'scotland':{division:'scotland',events:[{title:'Test holiday',date:'2026-10-10'}]}}),async()=>{const v={...event().venue,countryCode:'GB',state:'Scotland',timezone:'Europe/London'};const r=await require('@/lib/bank-holidays').checkBankHolidays(event({venue:v}));assert.equal(r.data[0].title,'Test holiday');const outside=await require('@/lib/bank-holidays').checkBankHolidays(event({venue:v,dateTime:'2030-10-10T18:00'}));assert.equal(outside.state,'out_of_range');}));
test('TfL chooses matching validity rather than an unrelated first window',()=>{const p=require('@/lib/tfl').tflPeriods([{from:'2026-09-10T00:00:00Z',to:'2026-09-11T00:00:00Z'},{from:'2026-10-10T17:00:00Z',to:'2026-10-10T22:00:00Z'}],event());assert.equal(p.length,1);assert.equal(p[0].startsAt,'2026-10-10T17:00:00.000Z');});
test('TfL validates the StopPoint response instead of treating errors as no stops',()=>mocked(()=>reply({message:'Wrong shape'}),async()=>{const r=await require('@/lib/tfl').checkTfLDisruptions(event({venue:{...event().venue,lat:51.5,lng:-0.12,countryCode:'GB',state:'England',timezone:'Europe/London'}}));assert.equal(r.state,'unavailable');}));

test('OpenHolidays requests public and school data and respects inclusive end date',()=>mocked(u=>reply(u.pathname==='/Countries'?[{isoCode:'PT'}]:u.pathname==='/PublicHolidays'?[{id:'holiday',nationwide:true,name:[{language:'EN',text:'Example holiday'}],startDate:'2026-10-10',endDate:'2026-10-10'}]:[]),async calls=>{const r=await G.checkOpenHolidays(event());assert.equal(calls.length,3);assert.equal(r.data[0].endsAt,'2026-10-10T23:00:00.000Z');}));
test('An unmatchable holiday subdivision remains incomplete, not invented',()=>mocked(u=>reply(u.pathname==='/Countries'?[{isoCode:'PT'}]:u.pathname==='/PublicHolidays'?[{id:'holiday',nationwide:false,subdivisions:[{code:'PT-99'}],name:[{language:'EN',text:'Local holiday'}],startDate:'2026-10-10',endDate:'2026-10-10'}]:[]),async()=>{const r=await G.checkOpenHolidays(event());assert.equal(r.state,'partial');assert.equal(r.data.length,0);}));

test('GDELT is opt-in and receives city words, not guessed coordinates',()=>mocked(u=>{assert.equal(u.pathname,'/api/v2/doc/doc');assert.equal(u.searchParams.get('mode'),'ArtList');assert.ok(!u.searchParams.get('query').includes('near:'));return reply({articles:[{url:'https://news.example.org/story',title:'Published notice',domain:'news.example.org',seendate:'20260922090000'}]});},async()=>{const r=await G.checkGdelt(event({includeNews:true}));assert.equal(r.state,'checked');assert.equal(r.scope,'current');assert.equal(r.data[0].timing,'unknown');assert.equal(r.data[0].distanceKm,undefined);assert.equal(r.data[0].startsAt,undefined);}));
test('GDELT is not called when news is disabled',()=>mocked(()=>{throw Error('No request expected');},async calls=>{assert.equal((await G.checkGdelt(event({includeNews:false}))).state,'not_applicable');assert.equal(calls.length,0);}));

test('IPMA district ISO code resolves Lisbon even with English state text',()=>{const a=active();return mocked(u=>reply(u.pathname.includes('distrits-islands')?{data:[{idDistrito:11,idAreaAviso:'LSB',local:'Lisboa'}]}:[{idAreaAviso:'LSB',awarenessLevelID:'yellow',awarenessTypeName:'Wind',startTime:a.start.replace('Z',''),endTime:a.end.replace('Z',''),text:'Official test warning'}]),async()=>{const r=await W.checkIpma(nowEvent({venue:{...event().venue,state:'Lisbon',subdivisionCode:'PT-11'}}));assert.equal(r.state,'checked');assert.equal(r.data[0].title,'yellow warning · Wind');assert.equal(r.data[0].resolutionEligible,false);});});
test('NWS uses point-matched active alerts and a real application identity',()=>withEnv({CONTACT_EMAIL:'test@example.org'},()=>mocked((u,o)=>{assert.equal(u.pathname,'/alerts');assert.equal(u.searchParams.get('active'),'true');assert.match(o.headers.get('User-Agent'),/test@example.org/);const a=active();return reply({features:[{properties:{id:'alert',status:'Actual',event:'Wind',headline:'Official warning',onset:a.start,ends:a.end,severity:'Severe',certainty:'Likely'}}]});},async()=>{const r=await W.checkNws(nowEvent({venue:{...event().venue,countryCode:'US',lat:40.7,lng:-74,timezone:'America/New_York'}}));assert.equal(r.state,'checked');assert.equal(r.scope,'current');assert.equal(r.data[0].resolutionEligible,false);})));
test('GDACS uses regional RSS context without an invented affected boundary',()=>mocked(()=>reply(`<rss xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#"><channel><item><title>Regional event</title><link>https://www.gdacs.org/report</link><geo:lat>38.72</geo:lat><geo:long>-9.14</geo:long><pubDate>${new Date().toUTCString()}</pubDate></item></channel></rss>`),async()=>{const r=await W.checkGdacs(nowEvent());assert.equal(r.scope,'current');assert.equal(r.data[0].resolutionEligible,false);assert.equal(r.data[0].relevance,'context');}));

test('EONET uses west/north/east/south bbox and observation context',()=>mocked(u=>{const b=u.searchParams.get('bbox').split(',').map(Number);assert.ok(b[0]<b[2]);assert.ok(b[1]>b[3]);return reply({events:[{id:'E',title:'Natural event',geometry:[{type:'Point',coordinates:[-9.14,38.72],date:new Date().toISOString()}],sources:[{id:'Agency',url:'https://agency.example.org/event'}]}]});},async()=>{const r=await G.checkEonet(nowEvent());assert.equal(r.data.length,1);assert.equal(r.data[0].resolutionEligible,false);assert.equal(r.scope,'current');}));
test('FIRMS uses area CSV MAP_KEY endpoint and does not call hotspots evacuations',()=>withEnv({FIRMS_MAP_KEY:'TEST_ONLY'},()=>mocked(u=>{assert.ok(u.pathname.startsWith('/api/area/csv/TEST_ONLY/VIIRS_SNPP_NRT/'));return reply('latitude,longitude,acq_date,acq_time,confidence\n38.72,-9.14,2026-09-22,1200,n\n');},async()=>{const r=await G.checkFirms(nowEvent());assert.equal(r.state,'checked');assert.equal(r.data[0].resolutionEligible,false);assert.match(r.data[0].title,/hotspot|heat detection/i);})));
test('USGS query is recent observations, not a future earthquake forecast',()=>mocked(u=>{assert.equal(u.pathname,'/fdsnws/event/1/query');assert.equal(u.searchParams.get('format'),'geojson');return reply({features:[{id:'E1',geometry:{type:'Point',coordinates:[-9.14,38.72,10]},properties:{mag:4,place:'Regional test',time:Date.now(),url:'https://earthquake.usgs.gov/earthquakes/eventpage/E1'}}]});},async()=>{const r=await G.checkUsgs(nowEvent());assert.equal(r.data[0].timing,'live');assert.equal(r.scope,'current');}));
test('Future gatherings do not trigger current-only natural event queries',()=>mocked(()=>{throw Error('No call');},async calls=>{for(const fn of [G.checkEonet,G.checkFirms,G.checkUsgs,W.checkGdacs])assert.equal((await fn(event({dateTime:'2030-01-01T18:00'}))).state,'not_applicable');assert.equal(calls.length,0);}));

test('Air-quality model preserves nulls and full event coverage',()=>withEnv({APP_USAGE:'noncommercial',OPEN_METEO_API_KEY:undefined},()=>mocked(u=>{assert.equal(u.searchParams.get('timeformat'),'unixtime');const w=eventWindow(event().dateTime,90,'Europe/Lisbon');return reply({hourly:{time:[w.start.getTime()/1000,w.start.getTime()/1000+3600],european_aqi:[60,null],pm2_5:[20,null],pm10:[30,null]}});},async()=>{const r=await G.checkAirQuality(event());assert.equal(r.state,'partial');assert.equal(r.data[0].resolutionEligible,false);})));
test('Commercial air-quality and Radar access cannot silently use restricted free data',()=>withEnv({APP_USAGE:'commercial',OPEN_METEO_API_KEY:undefined,RADAR_COMMERCIAL_PERMISSION:'false'},async()=>{assert.equal((await G.checkAirQuality(event())).state,'disabled');assert.equal((await G.checkRadar(nowEvent({needsInternet:true}))).state,'disabled');}));
test('SeatGeek credentials are Basic auth and an unknown event end remains context',()=>withEnv({SEATGEEK_CLIENT_ID:'TEST_ID',SEATGEEK_CLIENT_SECRET:'TEST_SECRET'},()=>mocked((u,o)=>{assert.equal(u.pathname,'/2/events');assert.equal(o.headers.get('Authorization'),'Basic '+Buffer.from('TEST_ID:TEST_SECRET').toString('base64'));assert.match(u.searchParams.get('datetime_utc.gte'),/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$/);return reply({meta:{total:1},events:[{id:123,title:'Listed event',datetime_utc:'2026-10-10T17:30:00',url:'https://seatgeek.com/event',venue:{name:'Venue',location:{lat:38.72,lon:-9.14}}}]});},async()=>{const r=await G.checkSeatGeek(event());assert.equal(r.data[0].relevance,'context');assert.equal(r.data[0].endsAt,undefined);})));
test('Radar reads documented annotations, uses bearer auth and remains regional',()=>withEnv({APP_USAGE:'noncommercial',CLOUDFLARE_RADAR_TOKEN:'TEST_ONLY'},()=>mocked((u,o)=>{assert.equal(u.pathname,'/client/v4/radar/annotations/outages');assert.equal(o.headers.get('Authorization'),'Bearer TEST_ONLY');assert.equal(u.searchParams.get('location'),'PT');return reply({success:true,result:{annotations:[{id:'outage',description:'Regional network interruption',startDate:new Date().toISOString(),linkedUrl:'https://radar.cloudflare.com/outage'}]}});},async()=>{const r=await G.checkRadar(nowEvent({needsInternet:true}));assert.equal(r.scope,'current');assert.equal(r.data[0].resolutionEligible,false);assert.equal(r.data[0].distanceKm,undefined);})));

test('Geocode text search does not accidentally reverse-geocode 0,0',()=>withEnv({GEOAPIFY_API_KEY:'TEST_ONLY'},()=>mocked(u=>{assert.equal(u.pathname,'/v1/geocode/autocomplete');assert.equal(u.searchParams.get('text'),'Lisbon');return reply({results:[{formatted:'Lisbon',lat:38.72,lon:-9.14,country_code:'pt',city:'Lisbon',state:'Lisboa',timezone:{name:'Europe/Lisbon'}}]});},async()=>{const {NextRequest}=require('next/server');const r=await require('@/app/api/geocode/route').GET(new NextRequest('http://localhost:3000/api/geocode?q=Lisbon'));assert.equal(r.status,200);})));


test('OpenHolidays does not call an unpublished empty year holiday-free',()=>mocked(u=>{if(u.pathname==='/Countries')return reply([{isoCode:'PT'}]);assert.equal(u.searchParams.get('validFrom'),'2026-01-01');assert.equal(u.searchParams.get('validTo'),'2026-12-31');return reply([]);},async()=>{const r=await G.checkOpenHolidays(event());assert.equal(r.state,'partial');assert.equal(r.data.length,0);}));
test('SeatGeek missing client secret is setup state, not a live API failure',()=>withEnv({SEATGEEK_CLIENT_ID:'TEST_ONLY',SEATGEEK_CLIENT_SECRET:undefined},()=>mocked(()=>{throw Error('No request expected');},async calls=>{assert.equal((await G.checkSeatGeek(event())).state,'not_configured');assert.equal(calls.length,0);})));
