const { test } = require('node:test');
const assert = require('node:assert/strict');
const { event, reply, mocked, fixtureFeed, field: f, pb } = require('./helpers.cjs');
const time = require('@/lib/time');
const { validateEvent, validatePreferences } = require('@/lib/validation');
const { parseXml, descendants, value } = require('@/lib/parsers/xml');
const { parseCsv } = require('@/lib/parsers/csv');
const { geometryDistance } = require('@/lib/parsers/geometry');
const { parseCapDocuments } = require('@/lib/parsers/cap');
const { parseDatex } = require('@/lib/parsers/datex');
const { parseIcal } = require('@/lib/parsers/ical');
const { decodeGtfs } = require('@/lib/parsers/gtfs');
const { parseWzdx, normalizeCivic, scopedGtfs, parsePublicFeed } = require('@/lib/connectors/regional');
const { validateFeeds } = require('@/lib/connectors/feed-config');
const { publicAddress } = require('@/lib/connectors/feed-http');

test('venue wall time becomes the correct UTC instant', () => assert.equal(time.zonedLocalToUtc('2026-07-01T19:00', 'Europe/Lisbon').toISOString(), '2026-07-01T18:00:00.000Z'));
test('invalid calendar day cannot silently roll into next month', () => assert.throws(() => time.zonedLocalToUtc('2026-02-30T19:00', 'UTC')));
test('spring DST nonexistent time is rejected', () => assert.throws(() => time.zonedLocalToUtc('2026-03-29T01:30', 'Europe/Lisbon')));
test('fall DST repeated time resolves explicitly to first occurrence', () => { const a = time.possibleInstants('2026-10-25T01:30', 'Europe/Lisbon'); assert.equal(a.length, 2); assert.equal(a[0].toISOString(), '2026-10-25T00:30:00.000Z'); });
test('end boundary is non-overlapping', () => assert.equal(time.overlaps(new Date(0), new Date(60), new Date(60), new Date(120)), false));
test('validation whitelists properties instead of trusting the posted report', () => { const e = validateEvent({ ...event(), injected: 'secret', conflicts: [{}] }); assert.equal(e.injected, undefined); assert.equal(e.conflicts, undefined); });
test('invalid coordinates, duration, radius and preferences are rejected', () => { assert.throws(() => validateEvent(event({ venue: { ...event().venue, lat: NaN } }))); assert.throws(() => validateEvent(event({ durationMinutes: -1 }))); assert.throws(() => validateEvent(event({ radiusKm: 500 }))); assert.throws(() => validatePreferences(JSON.parse('{"__proto__":"avoid"}'))); });
test('CSV handles escaped quotes, commas and a UTF-8 BOM', () => { const rows = parseCsv('\ufeffname,description\r\n"a,b","A ""quote"""\r\n'); assert.equal(rows[0].name, 'a,b'); assert.equal(rows[0].description, 'A "quote"'); });
test('XML uses local namespace names and decodes entities without fetching', () => { const r = parseXml('<root><cap:item><title>A &amp; B</title></cap:item></root>'); assert.equal(value(descendants(r, 'item')[0], 'title'), 'A & B'); });
test('XML rejects external entity and document type declarations', () => assert.throws(() => parseXml('<!DOCTYPE x [<!ENTITY xx SYSTEM "file:///etc/passwd">]><x>&xx;</x>')));
test('geometry: venue inside polygon, hole excluded, no fictitious MultiPoint line', () => {
  const e = event({ venue: { ...event().venue, lat: 0, lng: 0 } });
  const ring = [[-1,-1],[1,-1],[1,1],[-1,1],[-1,-1]];
  assert.equal(geometryDistance(e, { type: 'Polygon', coordinates: [ring] }), 0);
  const hole = [[-.1,-.1],[-.1,.1],[.1,.1],[.1,-.1],[-.1,-.1]];
  assert.ok(geometryDistance(e, { type: 'Polygon', coordinates: [ring,hole] }) > 1);
  assert.ok(geometryDistance(e, { type: 'MultiPoint', coordinates: [[-1,0],[1,0]] }) > 100);
});
function cap(id = 'one', status = 'Actual', type = 'Alert', refs = '') { return `<alert xmlns="urn:oasis:names:tc:emergency:cap:1.2"><identifier>${id}</identifier><sender>official</sender><sent>2026-10-10T12:00:00Z</sent><status>${status}</status><msgType>${type}</msgType><scope>Public</scope>${refs ? `<references>${refs}</references>` : ''}<info><language>en</language><event>Wind</event><severity>Severe</severity><certainty>Likely</certainty><urgency>Expected</urgency><effective>2026-10-10T16:00:00Z</effective><expires>2026-10-10T21:00:00Z</expires><headline>Wind warning</headline><area><areaDesc>Test area</areaDesc><polygon>38.70,-9.16 38.74,-9.16 38.74,-9.12 38.70,-9.12 38.70,-9.16</polygon></area></info></alert>`; }
test('CAP polygon order is lat/lon and venue containment is required', () => { const r = parseCapDocuments([cap()], event(), fixtureFeed('cap')); assert.equal(r.data.length, 1); assert.equal(r.data[0].resolutionEligible, false); assert.equal(parseCapDocuments([cap()], event({ venue: { ...event().venue, lat: 40 } }), fixtureFeed('cap')).data.length, 0); });
test('CAP test alerts and cancelled referenced alerts are excluded', () => { assert.equal(parseCapDocuments([cap('x','Test')], event(), fixtureFeed('cap')).data.length, 0); assert.equal(parseCapDocuments([cap(),cap('cancel','Actual','Cancel','official,one,2026-10-10T12:00:00Z')], event(), fixtureFeed('cap')).data.length, 0); });
test('CAP unsupported geocode is partial rather than a false no-warning result', () => { const xml = cap().replace(/<polygon>.*?<\/polygon>/, '<geocode><valueName>area</valueName><value>123</value></geocode>'); const r = parseCapDocuments([xml], event(), fixtureFeed('cap')); assert.equal(r.partial, true); assert.equal(r.data.length, 0); });
test('DATEX II supports explicit point coordinates and bounded validity', () => { const xml = '<d2:payloadPublication xmlns:d2="x" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="SituationPublication"><situation><situationRecord id="r1" xsi:type="RoadOrCarriagewayOrLaneManagement"><validity><validityStatus>active</validityStatus><validityTimeSpecification><overallStartTime>2026-10-10T16:00:00Z</overallStartTime><overallEndTime>2026-10-10T21:00:00Z</overallEndTime></validityTimeSpecification></validity><locationForDisplay><latitude>38.72</latitude><longitude>-9.14</longitude></locationForDisplay><comment><values><value>Road closed</value></values></comment></situationRecord></situation></d2:payloadPublication>'; const r = parseDatex(xml, event(), fixtureFeed('datex')); assert.equal(r.data.length, 1); assert.equal(r.data[0].timing, 'scheduled'); });
function ics(extra = '', start = '20261010T170000Z', end = '20261010T190000Z') { return `BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nUID:event-one\r\nDTSTART:${start}\r\nDTEND:${end}\r\nSUMMARY:Street festival\r\nGEO:38.72;-9.14\r\n${extra}\r\nEND:VEVENT\r\nEND:VCALENDAR`; }
test('ICS UTC bounded event overlaps and carries explicit provenance', () => { const r = parseIcal(ics(), event(), fixtureFeed('ics')); assert.equal(r.data.length, 1); assert.equal(r.data[0].title, 'Street festival'); assert.equal(r.data[0].resolutionEligible, true); });
test('ICS daily recurrence respects EXDATE', () => { const r = parseIcal(ics('RRULE:FREQ=DAILY;COUNT=20\r\nEXDATE:20261010T170000Z', '20261001T170000Z','20261001T190000Z'), event(), fixtureFeed('ics')); assert.equal(r.data.length, 0); });
test('ICS weekly recurrence returns correct weekday and unknown monthly rule is partial', () => { const r = parseIcal(ics('RRULE:FREQ=WEEKLY;BYDAY=SA;COUNT=3','20261003T170000Z','20261003T190000Z'), event(), fixtureFeed('ics')); assert.equal(r.data.length, 1); assert.equal(parseIcal(ics('RRULE:FREQ=MONTHLY'), event(), fixtureFeed('ics')).partial, true); });
test('ICS missing location is not silently geocoded from title', () => { const c = fixtureFeed('ics'); delete c.staticLocation; const r = parseIcal(ics().replace('GEO:38.72;-9.14\r\n',''), event(), c); assert.equal(r.partial, true); assert.equal(r.data.length, 0); });
function gtfs(timestamp = Math.floor(Date.now()/1000), differential = 0) { const range = pb(f(1,Date.parse('2026-10-10T16:00:00Z')/1000),f(2,Date.parse('2026-10-10T21:00:00Z')/1000)); const translation = f(1,pb(f(1,'Stop closed'),f(2,'en'))); const alert = pb(f(1,range),f(5,pb(f(5,'STOP-A'))),f(7,1),f(10,translation),f(14,4)); return pb(f(1,pb(f(1,'2.0'),f(2,differential),f(3,timestamp))),f(2,pb(f(1,'alert-one'),f(5,alert)))); }
test('GTFS protobuf decoder uses correct Alert fields and scoped stops', () => { const decoded = decodeGtfs(gtfs()); assert.equal(decoded.alerts.length, 1); const r = scopedGtfs(gtfs(),event(),fixtureFeed('gtfs',{gtfs:{stopIds:['STOP-A']}})); assert.equal(r.data.length, 1); assert.match(r.data[0].title,/Stop closed/); assert.equal(scopedGtfs(gtfs(),event(),fixtureFeed('gtfs',{gtfs:{stopIds:['OTHER']}})).data.length,0); });
test('GTFS rejects stale and differential snapshots rather than empty success', () => { assert.throws(()=>scopedGtfs(gtfs(1),event(),fixtureFeed('gtfs',{gtfs:{stopIds:['STOP-A']}}))); assert.throws(()=>scopedGtfs(gtfs(undefined,1),event(),fixtureFeed('gtfs',{gtfs:{stopIds:['STOP-A']}}))); assert.throws(()=>decodeGtfs(Uint8Array.from([10,255]))); });
test('WZDx schema reads core_details and UTC planned work periods', () => { const raw = {type:'FeatureCollection',feed_info:{version:'4.2',update_date:new Date().toISOString()},features:[{id:'road',type:'Feature',geometry:{type:'Point',coordinates:[-9.14,38.72]},properties:{core_details:{event_type:'work-zone',road_names:['Test Road'],description:'Lane closed'},start_date:'2026-10-10T16:00:00Z',end_date:'2026-10-10T20:00:00Z',work_zone_type:'static',vehicle_impact:'some-lanes-closed'}}]}; const r=parseWzdx(raw,event(),fixtureFeed('wzdx'));assert.equal(r.data.length,1);assert.match(r.data[0].title,/Test Road/); });
test('civic publication date is context, never scheduled incident time', () => { const c=fixtureFeed('arcgis',{fields:{id:'id',title:'title',start:'published'},timeMode:'published'});const r=normalizeCivic([{id:'1',title:'Notice',published:new Date().toISOString()}],event({dateTime:new Date(Date.now()+3600000).toISOString().slice(0,16),venue:{...event().venue,timezone:'UTC'}}),c);assert.equal(r.data[0].resolutionEligible,false);assert.equal(r.data[0].relevance,'context'); });
test('RSS publication timestamps remain observations, no future date inferred', () => { const xml=`<rss><channel><item><guid>one</guid><title>Road notice</title><pubDate>${new Date().toUTCString()}</pubDate><link>https://feed.example.org/one</link></item></channel></rss>`;const r=parsePublicFeed(xml,event(),fixtureFeed('rss'));assert.equal(r.data.length,1);assert.equal(r.data[0].startsAt,undefined);assert.equal(r.data[0].resolutionEligible,false); });
test('configuration rejects duplicate feeds, insecure URLs and embedded credentials', () => {const c=fixtureFeed('rss');assert.throws(()=>validateFeeds([c,c]));assert.throws(()=>validateFeeds([{...c,endpoint:'http://feed.example.org'}]));assert.throws(()=>validateFeeds([{...c,endpoint:'https://secret:password@feed.example.org'}]));});
test('SSRF public-address validator blocks metadata, private and loopback addresses', () => {for(const ip of ['127.0.0.1','10.0.0.1','169.254.169.254','192.168.1.1','::1','fc00::1'])assert.equal(publicAddress(ip),false);assert.equal(publicAddress('8.8.8.8'),true);});
test('HTTP deduplicates concurrent requests', async () => {const {getJson}=require('@/lib/http');await mocked(()=>reply({ok:true}),async calls=>{await Promise.all([getJson('https://example.org/data'),getJson('https://example.org/data')]);assert.equal(calls.length,1);});});
test('HTTP 429 is unavailable, cached as cooldown and secrets stay out of safe errors', async()=>{const {getJson,safeMessage}=require('@/lib/http');await mocked(()=>reply({key:'do-not-display'},429,{'retry-after':'60'}),async calls=>{await assert.rejects(getJson('https://example.org/data?apikey=secret'));await assert.rejects(getJson('https://example.org/other'));assert.equal(calls.length,1);assert.doesNotMatch(safeMessage(new Error('apikey=secret')),/secret/);});});
test('HTTP honours no-store and rejects oversized payloads',async()=>{const {getJson}=require('@/lib/http');await mocked(()=>reply({},200,{'cache-control':'no-store'}),async calls=>{await getJson('https://example.org/no');await getJson('https://example.org/no');assert.equal(calls.length,2);});await mocked(()=>reply({},200,{'content-length':'6000000'}),()=>assert.rejects(getJson('https://example.org/big')));});
