const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const {event,reply,mocked,fixtureFeed,withEnv}=require('./helpers.cjs');
const R=require('@/lib/connectors/regional');const D=require('@/lib/connectors/discovery');
const {validateFeeds}=require('@/lib/connectors/feed-config');
const {instantToLocal}=require('@/lib/time');
const fields={id:'id',title:'title',start:'start',end:'end',lat:'lat',lon:'lon'};
const row={id:'1',title:'City works',start:'2026-10-10T17:00:00Z',end:'2026-10-10T20:00:00Z',lat:38.72,lon:-9.14};
async function publicDns(fn){const dns=require('node:dns/promises'),old=dns.lookup;dns.lookup=async()=>[{address:'8.8.8.8',family:4}];try{return await fn();}finally{dns.lookup=old;}}

test('ArcGIS sends spatial WGS84 layer queries and reads GeoJSON properties',()=>publicDns(()=>mocked((u)=>{assert.ok(u.pathname.endsWith('/FeatureServer/0/query'));assert.equal(u.searchParams.get('f'),'geojson');assert.equal(u.searchParams.get('inSR'),'4326');assert.equal(u.searchParams.get('spatialRel'),'esriSpatialRelIntersects');return reply({type:'FeatureCollection',features:[{type:'Feature',geometry:{type:'Point',coordinates:[-9.14,38.72]},properties:row}]});},async()=>{const r=await R.queryCivic(event(),fixtureFeed('arcgis',{endpoint:'https://feed.example.org/FeatureServer/0',fields}));assert.equal(r.data[0].title,'City works');assert.equal(r.data[0].resolutionEligible,true);})));
test('Socrata uses SODA3 POST, JSON and a token; pagination is one based',()=>withEnv({TEST_SODA_TOKEN:'TEST_ONLY'},()=>publicDns(()=>mocked((u,o)=>{assert.equal(u.pathname,'/api/v3/views/abcd-1234/query.json');assert.equal(o.method,'POST');assert.equal(o.headers.get('Content-Type'),'application/json');assert.equal(o.headers.get('X-App-Token'),'TEST_ONLY');const b=JSON.parse(o.body);assert.equal(b.page.pageNumber,1);assert.equal(b.includeSynthetic,false);assert.ok(!b.query.includes('{{start}}'));return reply([row]);},async()=>{const r=await R.queryCivic(event(),fixtureFeed('socrata',{endpoint:'https://feed.example.org',datasetId:'abcd-1234',auth:{env:'TEST_SODA_TOKEN',header:'X-App-Token'},fields,where:"start < '{{end}}'",orderBy:'id'}));assert.equal(r.data.length,1);}))));
test('CKAN checks success:false even when the HTTP status is 200',()=>publicDns(()=>mocked(()=>reply({success:false,error:{message:'No resource'}}),async()=>{const r=await R.checkRegionalFeed(event(),fixtureFeed('ckan',{endpoint:'https://feed.example.org',resourceId:'abc',fields}));assert.equal(r.state,'unavailable');})));
test('CKAN DataStore reads mapped fields and tracks bounded pagination',()=>publicDns(()=>mocked(u=>{assert.equal(u.searchParams.get('resource_id'),'abc');return reply({success:true,result:{total:1000,records:[row]}});},async calls=>{const r=await R.queryCivic(event(),fixtureFeed('ckan',{endpoint:'https://feed.example.org',resourceId:'abc',fields,pageLimit:1,limit:10}));assert.equal(calls.length,1);assert.equal(r.partial,true);assert.equal(r.data.length,1);})));
test('Open311 sends recent-open filters but does not expose reporter data',()=>publicDns(()=>mocked(u=>{assert.ok(u.pathname.endsWith('/requests.json'));assert.equal(u.searchParams.get('status'),'open');return reply([{service_request_id:'1',service_name:'Drain issue',status:'open',lat:38.72,long:-9.14,description:'PRIVATE REPORTER TEXT',first_name:'Private Name',media_url:'https://example.org/photo'}]);},async()=>{const e=event({dateTime:instantToLocal(new Date(Date.now()+3600000),'Europe/Lisbon').slice(0,16)});const r=await R.checkOpen311(e,fixtureFeed('open311'));assert.equal(r.data[0].evidence,'community');assert.ok(!JSON.stringify(r).includes('PRIVATE REPORTER'));assert.ok(!JSON.stringify(r).includes('Private Name'));})));
test('Missing regional credentials skip the request and never count as checked',()=>withEnv({TEST_FEED_KEY:undefined},()=>mocked(()=>{throw Error('No request');},async calls=>{const r=await R.checkRegionalFeed(event(),fixtureFeed('cap',{auth:{env:'TEST_FEED_KEY',header:'x-api-key'}}));assert.equal(r.state,'not_configured');assert.equal(calls.length,0);})));
test('Every shipped feed example and optional preset validates but remains disabled',()=>{for(const file of ['docs/feeds.examples.json','docs/presets/meteoalarm-portugal.json']){const rows=validateFeeds(JSON.parse(fs.readFileSync(file)));assert.ok(rows.length>0);assert.ok(rows.every(r=>r.enabled===false));}assert.deepEqual(validateFeeds(JSON.parse(fs.readFileSync('src/config/feeds.json'))),[]);});
test('Civic scheduled adapter does not invent geometry for a row without a location',()=>{const r=R.normalizeCivic([{id:'1',title:'Works',start:row.start,end:row.end}],event(),fixtureFeed('arcgis',{staticLocation:undefined,fields}));assert.equal(r.partial,true);assert.equal(r.data.length,0);});
test('Civic dataset publication timestamps are not occurrence timestamps',()=>{const c=fixtureFeed('arcgis',{fields:{id:'id',title:'title',updated:'published'},timeMode:'published'});const e=event({dateTime:instantToLocal(new Date(Date.now()+3600000),'Europe/Lisbon').slice(0,16)});const r=R.normalizeCivic([{id:'1',title:'Notice',published:new Date().toISOString()}],e,c);assert.equal(r.data[0].startsAt,undefined);assert.equal(r.data[0].resolutionEligible,false);});

test('Mobility CSV discovery joins GTFS-RT alerts to static feed country scope',()=>{const csv='id,data_type,entity_type,status,provider,location.country_code,static_reference,urls.direct_download\nstatic-one,gtfs,,active,Transit,PT,,https://feeds.example.org/static.zip\nrt-one,gtfs-rt,sa,active,Transit,,static-one,https://feeds.example.org/alerts.pb\nrt-two,gtfs-rt,vp,active,Transit,,static-one,https://feeds.example.org/vehicles.pb\n';const rows=D.mobilityRows(csv,'PT');assert.equal(rows.length,1);assert.equal(rows[0].id,'rt-one');assert.equal(rows[0].configured,false);assert.deepEqual(rows[0].staticReferences,['static-one']);assert.equal(D.mobilityRows(csv,'GB').length,0);});
test('Mobility auth exchanges refresh token then checks metadata without printing credentials',()=>withEnv({MOBILITY_DATABASE_REFRESH_TOKEN:'TEST_REFRESH'},()=>mocked((u,o)=>{if(u.pathname==='/v1/tokens'){assert.equal(o.method,'POST');assert.deepEqual(JSON.parse(o.body),{refresh_token:'TEST_REFRESH'});return reply({access_token:'TEST_ACCESS'});}assert.equal(u.pathname,'/v1/metadata');assert.equal(o.headers.get('Authorization'),'Bearer TEST_ACCESS');return reply({version:'test'});},async()=>{const r=await D.checkMobilityAccount();assert.equal(r.authenticated,true);assert.ok(!JSON.stringify(r).includes('TEST_ACCESS'));})));
test('ArcGIS discovery requests public Feature Services, not private account content',()=>mocked(u=>{assert.equal(u.pathname,'/sharing/rest/search');assert.match(u.searchParams.get('q'),/access:public/);return reply({total:1,nextStart:-1,results:[{id:'layer',title:'Road works',url:'https://services.example.org/FeatureServer'}]});},async()=>{const r=await D.discoverArcgis('Lisbon road works');assert.equal(r.results.length,1);assert.match(r.results[0].required,/Inspect/);}));

test('API rejects a cross-site request before calling providers',()=>{const {NextRequest}=require('next/server');const {guard}=require('@/lib/api-guard');const r=guard(new NextRequest('http://localhost/api/analyze',{headers:{origin:'https://hostile.example.org','sec-fetch-site':'cross-site'}}));assert.equal(r.status,403);});
test('API enforces JSON request bodies and preserves no raw upstream error text',async()=>{const {NextRequest}=require('next/server');const {readBody,apiError}=require('@/lib/api-guard');await assert.rejects(()=>readBody(new NextRequest('http://localhost/api/analyze',{method:'POST',body:'{}',headers:{'Content-Type':'text/plain'}})));const response=apiError(new Error('SECRET_KEY_EXAMPLE'));assert.ok(!(await response.text()).includes('SECRET_KEY_EXAMPLE'));});
