export interface ProviderInfo {
  id: string; name: string; category: string; docs: string; website: string;
  mode: 'automatic' | 'key' | 'feed' | 'discovery'; env?: string;
  coverage: string; licence: string; sends: string;
}
export const PROVIDERS: ProviderInfo[] = [
  {id:'geoapify',name:'Geoapify',category:'Location',mode:'key',env:'GEOAPIFY_API_KEY',docs:'https://apidocs.geoapify.com/docs/geocoding/',website:'https://www.geoapify.com/',coverage:'Address search, reverse geocoding and venue timezone.',licence:'Geoapify terms; free-plan attribution applies.',sends:'Search text or selected coordinates.'},
  {id:'ticketmaster',name:'Ticketmaster',category:'Events',mode:'key',env:'TICKETMASTER_API_KEY',docs:'https://developer.ticketmaster.com/products-and-docs/apis/discovery-api/v2/',website:'https://www.ticketmaster.com/',coverage:'Listed events only. Listing start times do not establish crowd size or event end times.',licence:'Ticketmaster API terms. Revenue-generating use requires permission; disabled in commercial mode unless explicitly approved.',sends:'Search area and event date range.'},
  {id:'football',name:'football-data.org',category:'Interests',mode:'key',env:'FOOTBALL_DATA_API_KEY',docs:'https://docs.football-data.org/',website:'https://www.football-data.org/',coverage:'Selected team, subject to your subscription and published fixtures. Match end times are estimates.',licence:'Provider terms; keep credentials confidential.',sends:'Team search and fixture date range.'},
  {id:'football-af',name:'API-Football',category:'Interests',mode:'key',env:'API_FOOTBALL_KEY',docs:'https://www.api-football.com/documentation-v3',website:'https://www.api-football.com/',coverage:'Selected teams worldwide across most national leagues and cups. Free plan allowance is about 100 requests/day, so fixture checks pace themselves.',licence:'Provider terms; keep credentials confidential.',sends:'Team search and selected fixture date ranges.'},
  {id:'tvmaze',name:'TVmaze',category:'Interests',mode:'automatic',docs:'https://www.tvmaze.com/api',website:'https://www.tvmaze.com/',coverage:'Only the programme explicitly selected.',licence:'CC BY-SA; attribution and applicable share-alike obligations.',sends:'Programme search, selected programme ID.'},
  {id:'bank-holidays',name:'UK bank holidays',category:'Calendar',mode:'automatic',docs:'https://www.gov.uk/bank-holidays.json',website:'https://www.gov.uk/bank-holidays',coverage:'England/Wales, Scotland and Northern Ireland.',licence:'Open Government Licence, where applicable.',sends:'No venue; the complete public calendar is fetched.'},
  {id:'weather',name:'MET Norway',category:'Weather',mode:'automatic',env:'MET_USER_AGENT',docs:'https://docs.api.met.no/doc/locationforecast/HowTO.html',website:'https://www.met.no/',coverage:'Published forecast horizon only.',licence:'CC BY 4.0. Identification and caching required.',sends:'Coordinates rounded to four decimal places; application identity.'},
  {id:'daylight',name:'Sunrise-Sunset',category:'Daylight',mode:'automatic',docs:'https://sunrise-sunset.org/api',website:'https://sunrise-sunset.org/',coverage:'Sunrise and sunset at the selected place/date; not a visibility guarantee.',licence:'Linked attribution; reasonable request volumes.',sends:'Coordinates and calendar date.'},
  {id:'tfl',name:'Transport for London',category:'Transport',mode:'key',env:'TFL_APP_KEY',docs:'https://api.tfl.gov.uk/',website:'https://tfl.gov.uk/',coverage:'Nearby stops and published line statuses in London.',licence:'TfL transport data terms. Contains Transport for London data.',sends:'Coordinates, nearby stop and line IDs, dates.'},
  {id:'tomtom',name:'TomTom Traffic',category:'Roads',mode:'key',env:'TOMTOM_API_KEY',docs:'https://docs.tomtom.com/traffic-api/documentation/tomtom-orbis-maps/v2/traffic-incidents/incident-details',website:'https://www.tomtom.com/',coverage:'Current and published future incidents returned for the search area. Not route-specific travel advice.',licence:'TomTom terms and your plan; attribution and caching restrictions apply.',sends:'A bounding box, not the venue address.'},
  {id:'transitland',name:'Transitland',category:'Transport',mode:'key',env:'TRANSITLAND_API_KEY',docs:'https://www.transit.land/documentation/concepts/alerts/',website:'https://www.transit.land/',coverage:'Alerts on returned nearby stops and selected serving routes/agencies. Trip-only alerts are not comprehensively covered.',licence:'Transitland terms plus each underlying agency/feed licence.',sends:'Coordinates, radius and nearby route/agency IDs.'},
  {id:'mobilitydb',name:'Mobility Database',category:'Transport discovery',mode:'discovery',env:'MOBILITY_DATABASE_REFRESH_TOKEN',docs:'https://mobilitydata.github.io/mobility-feed-api/SwaggerUI/index.html',website:'https://mobilitydatabase.org/',coverage:'Finds feeds. A catalogue entry does not mean its alerts have been connected.',licence:'Catalogue and individual source licences apply separately.',sends:'Country/area filters when the administrator runs discovery.'},
  {id:'gtfs',name:'GTFS-Realtime',category:'Transport',mode:'feed',docs:'https://gtfs.org/documentation/realtime/reference/',website:'https://gtfs.org/',coverage:'Configured full-dataset service-alert feeds and mapped stops/routes only.',licence:'The transport agency/feed licence, not the GTFS specification.',sends:'A configured feed request; normally no venue.'},
  {id:'gdelt',name:'GDELT news',category:'Local reports',mode:'automatic',docs:'https://blog.gdeltproject.org/gdelt-doc-2-0-api-debuts/',website:'https://www.gdeltproject.org/',coverage:'Recent headlines mentioning the city/country and disruption terms. No inferred incident location or occurrence time.',licence:'GDELT access is open; original publishers retain rights to their articles. Headlines and links only.',sends:'City/country names and general disruption keywords, only when enabled by the organiser.'},
  {id:'openholidays',name:'OpenHolidays',category:'Calendar',mode:'automatic',docs:'https://www.openholidaysapi.org/en/',website:'https://www.openholidaysapi.org/',coverage:'Published public and school calendars in supported countries/subdivisions. School groups may require local confirmation.',licence:'ODbL; attribution and applicable database share-alike obligations.',sends:'Country, subdivision and calendar date range.'},
  {id:'meteoalarm',name:'MeteoAlarm',category:'Official warnings',mode:'feed',docs:'https://api.meteoalarm.org/edr/v1',website:'https://www.meteoalarm.org/',coverage:'Configured public CAP/Atom feeds. Geocodes without geometry need an area mapping.',licence:'CC BY 4.0 and provider attribution; direct EDR API registration is separate.',sends:'Country feed request; no venue to the feed publisher.'},
  {id:'cap',name:'CAP warnings',category:'Official warnings',mode:'feed',docs:'https://docs.oasis-open.org/emergency/cap/v1.2/CAP-v1.2-os.html',website:'https://www.oasis-open.org/',coverage:'Public, actual alerts from approved feeds. Polygon/circle or configured geocode matching required.',licence:'Each alert publisher’s licence; CAP is only a format.',sends:'Configured feed requests, not a private calendar.'},
  {id:'ipma',name:'IPMA warnings',category:'Official warnings',mode:'automatic',docs:'https://api.ipma.pt/',website:'https://www.ipma.pt/',coverage:'Portuguese warning districts, using explicit district matching. Short published horizon.',licence:'IPMA attribution and reuse conditions; notify IPMA of use as requested in its API guidance.',sends:'No venue; the national warnings feed is fetched.'},
  {id:'nws',name:'US National Weather Service',category:'Official warnings',mode:'automatic',docs:'https://www.weather.gov/documentation/services-web-api',website:'https://www.weather.gov/',coverage:'US point-matched active warnings and their published validity; not a long-range warning forecast.',licence:'US government open data; identification and usage guidance apply.',sends:'Coordinates and application identity.'},
  {id:'gdacs',name:'GDACS',category:'Natural hazards',mode:'automatic',docs:'https://www.gdacs.org/xml/rss.xml',website:'https://www.gdacs.org/',coverage:'Official RSS disaster summaries; current regional context, not a venue safety boundary.',licence:'GDACS and originating data-provider conditions; keep source attribution.',sends:'No venue; public RSS is fetched.'},
  {id:'eonet',name:'NASA EONET',category:'Natural hazards',mode:'automatic',docs:'https://eonet.gsfc.nasa.gov/docs/v3',website:'https://eonet.gsfc.nasa.gov/',coverage:'Recent open natural events near the venue. Observation locations are not hazard perimeters.',licence:'NASA use guidance and original linked-source conditions.',sends:'Bounding box and recent date range.'},
  {id:'firms',name:'NASA FIRMS',category:'Fire observations',mode:'key',env:'FIRMS_MAP_KEY',docs:'https://firms.modaps.eosdis.nasa.gov/api/area/',website:'https://firms.modaps.eosdis.nasa.gov/',coverage:'Recent satellite hotspots; not confirmed fires, evacuation orders or forecasts.',licence:'NASA FIRMS citation and dataset conditions.',sends:'Bounding box and recent observation dates.'},
  {id:'usgs',name:'USGS earthquakes',category:'Natural hazards',mode:'automatic',docs:'https://earthquake.usgs.gov/fdsnws/event/1/',website:'https://earthquake.usgs.gov/',coverage:'Recent recorded earthquakes within a regional search radius; no predictions.',licence:'USGS public data and source-credit guidance.',sends:'Coordinates, radius and recent date range.'},
  {id:'datex',name:'DATEX II / National Access Points',category:'Roads',mode:'feed',docs:'https://docs.datex2.eu/v3.3/situation/',website:'https://transport.ec.europa.eu/transport-themes/smart-mobility/road/its-directive-and-action-plan/national-access-points_en',coverage:'Configured WGS84 situation feeds. Linear-referenced-only locations and complex recurrence require a local adapter.',licence:'Country/access-point dataset terms; DATEX II is not a universal data licence.',sends:'Configured feed request.'},
  {id:'wzdx',name:'WZDx work zones',category:'Roads',mode:'feed',docs:'https://github.com/usdot-jpo-ode/wzdx',website:'https://ops.fhwa.dot.gov/wz/wzdx/',coverage:'Configured GeoJSON work-zone feeds in participating US jurisdictions.',licence:'Each publisher’s data licence.',sends:'Configured feed request.'},
  {id:'arcgis',name:'ArcGIS civic data',category:'Municipal data',mode:'feed',docs:'https://developers.arcgis.com/rest/services-reference/enterprise/query-feature-service-layer/',website:'https://hub.arcgis.com/',coverage:'Configured public layers with explicit fields, dates and geometry.',licence:'Dataset-specific; public access alone is not permission to reuse.',sends:'Spatial search and date filters to the configured publisher.'},
  {id:'socrata',name:'Socrata civic data',category:'Municipal data',mode:'feed',docs:'https://dev.socrata.com/docs/queries/',website:'https://dev.socrata.com/',coverage:'Configured SODA3 datasets and explicit field mapping. App token required.',licence:'Dataset-specific; platform documentation licence is not the data licence.',sends:'Bounded dataset queries and optional geographic/time filters.'},
  {id:'ckan',name:'CKAN civic data',category:'Municipal data',mode:'feed',docs:'https://docs.ckan.org/en/latest/api/',website:'https://ckan.org/',coverage:'Configured DataStore resources. Package search is discovery only.',licence:'Dataset-specific; CKAN software licensing does not license the data.',sends:'Configured resource ID and bounded row queries.'},
  {id:'open311',name:'Open311',category:'Community reports',mode:'feed',docs:'https://wiki.open311.org/GeoReport_v2/',website:'https://www.open311.org/',coverage:'Recent open public service requests, not verified hazards. Personal descriptions/media are not displayed.',licence:'Municipal dataset-specific reuse and privacy conditions.',sends:'Request date/status filters; results are filtered locally by coordinates.'},
  {id:'airquality',name:'Open-Meteo air quality',category:'Environment',mode:'automatic',env:'OPEN_METEO_API_KEY',docs:'https://open-meteo.com/en/docs/air-quality-api',website:'https://open-meteo.com/',coverage:'Modelled hourly air quality during the published forecast window; not a local sensor or medical assessment.',licence:'CC BY 4.0 data with attribution to Open-Meteo and CAMS. Free hosted API is non-commercial; commercial use needs an eligible plan.',sends:'Coordinates and requested variables.'},
  {id:'seatgeek',name:'SeatGeek',category:'Events',mode:'key',env:'SEATGEEK_CLIENT_ID',docs:'https://seatgeek.github.io/',website:'https://seatgeek.com/',coverage:'Events available to your approved API credentials. Unknown end times remain uncertain.',licence:'SeatGeek platform terms and your approved access plan. Free access is not guaranteed.',sends:'Coordinates, range and event-date filters.'},
  {id:'radar',name:'Cloudflare Radar',category:'Internet',mode:'key',env:'CLOUDFLARE_RADAR_TOKEN',docs:'https://developers.cloudflare.com/api/resources/radar/subresources/annotations/subresources/outages/methods/get/',website:'https://radar.cloudflare.com/',coverage:'Recent country/regional outage annotations, only when internet matters. Not venue connectivity monitoring.',licence:'Radar data is CC BY-NC 4.0 unless separately licensed; commercial mode requires explicit permission.',sends:'Country and recent date range.'},
  {id:'feeds',name:'Official RSS / Atom / ICS',category:'Local notices',mode:'feed',docs:'https://www.rfc-editor.org/rfc/rfc5545',website:'https://www.rfc-editor.org/',coverage:'Configured public notices and calendars. News publication date is not an event time. Supported calendar recurrence is bounded.',licence:'Publisher-specific; only authorised public feeds, never private calendars.',sends:'Configured feed request.'},
];
export const provider = (id: string): ProviderInfo => {
  const p = PROVIDERS.find(p => p.id === id); if (!p) throw new Error('Unknown provider'); return p;
};
