 'use client';
import Link from 'next/link';
import { useState } from 'react';
import Logo from './Logo';
import Credits from './Credits';
import { Conflict,EventPreference,PreferenceOverrides,Report,SourceStatus,Suggestion } from '@/types';
import { formatLocalDateTime,formatInstant } from '@/lib/time';
import { preferenceFor,preferenceKey } from '@/lib/preferences';
const TYPES:Record<Conflict['type'],string>={nearby_event:'Event',sport:'Football',tv:'TV',holiday:'Holiday',weather:'Weather',daylight:'Daylight',transport:'Transport',road:'Roads',warning:'Official warning',hazard:'Natural event',air_quality:'Air quality',news:'News report',civic:'Local notice',internet:'Internet'};
const EVIDENCE:Record<NonNullable<Conflict['evidence']>,string>={official:'Official source',structured:'Published listing',observed:'Observation / model',reported:'Reported in news',community:'Community report'};
const PREFS:Array<[EventPreference,string]>=[['avoid','Avoid it'],['neutral',"Doesn’t matter"],['plan_around','Plan around it']];
export function sourceState(source:SourceStatus):string{if(source.state==='checked')return source.scope==='current'?'Current reports checked':'Checked';return ({partial:'Limited coverage',unavailable:'Unavailable',out_of_range:'Outside available dates',not_configured:'Not connected',disabled:'Disabled',not_applicable:'Not relevant here'} as const)[source.state];}
interface Props{report:Report;preferences:PreferenceOverrides;recommendationBusy:boolean;recommendationDirty:boolean;onPreference:(id:string,p:EventPreference)=>void;onRecalculate:(mode:'earlier'|'another_day')=>void;onApply:(s:Suggestion)=>void;onEdit:()=>void;onRerun:()=>void;}
export function FindingCard({conflict:c,preference,onChange,timezone}:{conflict:Conflict;preference:EventPreference;onChange:(p:EventPreference)=>void;timezone:string}){
 const dated=c.startsAt&&(c.timing==='scheduled'||c.timing==='forecast');
 return <article className={`finding-card impact-${c.impact}`}><div className="finding-body"><div className="finding-kicker">{TYPES[c.type]} <span className="evidence-tag">{EVIDENCE[c.evidence??'structured']}</span></div><h3>{c.title}</h3>{c.description&&<p>{c.description}</p>}
 {dated&&<p className="finding-time">{formatInstant(c.startsAt!,timezone)}{c.endsAt?` → ${formatInstant(c.endsAt,timezone)}`:' · End time not published'}</p>}
 <div className="finding-meta">{c.distanceKm!==undefined&&<span>{c.distanceKm<.1?'Within the selected area':`${c.distanceKm.toFixed(1)} km from pin`}</span>}{c.areaLabel&&<span>{c.areaLabel}</span>}{c.sourceUrl&&<a href={c.sourceUrl} target="_blank" rel="noreferrer">{c.source} ↗</a>}{c.observedAt&&<span>Reported / observed {formatInstant(c.observedAt,timezone)}</span>}</div>
 {c.caveat&&<p className="finding-caveat">{c.caveat}</p>}</div><div className="intent-control" role="group" aria-label={`How to treat ${c.title}`}>{PREFS.map(([v,label])=><button key={v} type="button" aria-pressed={preference===v} className={preference===v?`active ${v}`:''} onClick={()=>onChange(v)}>{label}</button>)}</div></article>;
}
function SuggestionCard({suggestion:s,onApply}:{suggestion:Suggestion;onApply:()=>void}){
 const sections:Array<[string,string[]|undefined]>=[['No longer overlaps',s.conflictsResolved],['Still overlaps',s.conflictsRemaining],['Still needs checking',s.unresolvedContext],['New trade-offs',s.conflictsAdded],['Keeps your plan around',s.planAroundKept],['Loses your plan around',s.planAroundLost],['Closer to the start of',s.planAroundImproved]];
 return <article className="suggestion-card primary"><div className="suggestion-head"><span>Best of the times checked</span><strong>{s.candidateCount??1} checked</strong></div><h3>{s.change}</h3><div className="suggestion-columns">{sections.filter(([,v])=>v?.length).map(([label,items])=><div key={label}><b>{label}</b><p>{items!.join(' · ')}</p></div>)}</div><p className="suggestion-note">{s.coverageNote}</p><button className="pixel-button invert" type="button" onClick={onApply}>Use this time</button></article>;
}
export default function ReportView({report,preferences,recommendationBusy,recommendationDirty,onPreference,onRecalculate,onApply,onEdit,onRerun}:Props){
 const [expanded,setExpanded]=useState(false),[contextExpanded,setContextExpanded]=useState(false);
 const timed=report.conflicts.filter(c=>c.relevance==='overlap'),context=report.conflicts.filter(c=>c.relevance!=='overlap');
 const avoid=timed.filter(c=>preferenceFor(c,preferences)==='avoid');
 const failed=report.sources.filter(s=>['partial','unavailable','out_of_range'].includes(s.state));
 const configured=report.sources.filter(s=>!['not_configured','disabled','not_applicable'].includes(s.state)&&s.id!=='geoapify');
 const noChecks=!configured.some(s=>['checked','partial'].includes(s.state)&&s.scope!=='current'&&s.scope!=='discovery');
 const timezone=report.event.venue.timezone!;
 const card=(c:Conflict)=><FindingCard key={c.id} conflict={c} preference={preferenceFor(c,preferences)} onChange={v=>onPreference(preferenceKey(c),v)} timezone={timezone}/>;
 return <div className="report-page"><header className="site-header report-topbar"><button type="button" className="brand-button brand" onClick={onEdit}><Logo size={30}/><strong>BAD TIMING</strong></button><div className="report-actions"><Link className="plain-link" href="/sources">Sources</Link><button type="button" className="pixel-button ghost" disabled={recommendationBusy} onClick={onRerun}>Check again</button><button type="button" className="pixel-button" onClick={onEdit}>Edit</button></div></header>
 <main className="report-shell"><section className={`verdict-block ${avoid.length||noChecks?'warn':'clear'}`}><div className="verdict-code" aria-hidden="true">{avoid.length||noChecks?'!':'·'}</div><div><p className="report-context">{formatLocalDateTime(report.event.dateTime)} · {report.event.venue.name||report.event.venue.address}</p><h1>{noChecks?'Could not check this date':avoid.length?`${avoid.length} ${avoid.length===1?'overlap':'overlaps'} to consider`:'No overlap found in checked schedules'}</h1><p className="verdict-copy">{report.event.durationMinutes} min · {report.event.isOutdoor?'Outdoor':'Indoor'} · {timezone}</p><p className="report-timestamp">Checked {formatInstant(report.checkedAt,timezone)}</p></div></section>
 {(report.notices??[]).map(n=><aside className="coverage-warning" key={n}>{n}</aside>)}
 {failed.length>0&&<aside className="coverage-warning"><span>Some checks are incomplete. <a href="#source-details">View coverage</a></span></aside>}
 <section className="report-section"><div className="section-heading"><h2>At this time</h2>{timed.length>3&&<button className="text-button" type="button" onClick={()=>setExpanded(!expanded)}>{expanded?'Show less':`Show all ${timed.length}`}</button>}</div><div className="findings-list">{(expanded?timed:timed.slice(0,3)).map(card)}</div>{!timed.length&&<div className="empty-pixel"><p>No dated overlap surfaced. This does not confirm that the place is clear or safe.</p></div>}</section>
 {context.length>0&&<section className="report-section context-section"><div className="section-heading"><h2>Check locally</h2>{context.length>3&&<button className="text-button" type="button" onClick={()=>setContextExpanded(!contextExpanded)}>{contextExpanded?'Show less':`Show all ${context.length}`}</button>}</div><p className="section-note">Recent reports, regional conditions, or incomplete event times. A date change does not prove these are resolved.</p><div className="findings-list">{(contextExpanded?context:context.slice(0,3)).map(card)}</div></section>}
 <section className="report-section recommendation-zone"><div className="section-heading"><h2>Try another time</h2></div><div className="alternative-controls"><button type="button" className="pixel-button accent" disabled={recommendationBusy} onClick={()=>onRecalculate('earlier')}>Same day · earlier</button><button type="button" className="pixel-button" disabled={recommendationBusy} onClick={()=>onRecalculate('another_day')}>Same time · another day</button></div>
 {recommendationBusy?<div className="recommendation-loading" role="status"><span className="scanner-line"/><strong>Checking candidate times…</strong></div>:recommendationDirty?<p className="section-note">Choose what matters, then check one of the options above.</p>:report.suggestions.length?<div className="suggestion-stack">{report.suggestions.map(s=><SuggestionCard key={s.newDateTime} suggestion={s} onApply={()=>onApply(s)}/>)}</div>:<div className="no-change-card"><p>{report.alternativeNote||'No verified improvement among the times checked.'}</p></div>}</section>
 <details className="sources-panel" id="source-details"><summary><span>Connections & coverage</span><span>Details</span></summary><p className="section-note">“Checked” means the configured query succeeded, not that every event or incident is covered.</p><div className="source-grid">{report.sources.map(s=><div key={s.id} className={`source-row state-${s.state}`}><i/><span><a href={s.url} target="_blank" rel="noreferrer"><b>{s.name} ↗</b></a><small>{sourceState(s)}</small>{s.message&&<small>{s.message}</small>}{s.fetchedAt&&<small>Fetched {formatInstant(s.fetchedAt,timezone)}</small>}{s.limitations?.map(l=><small key={l}>{l}</small>)}</span></div>)}</div></details><Credits/></main></div>;
}
