import InfoLayout from '@/components/InfoLayout';
import {deploymentDetails} from '@/lib/deployment';
export const dynamic='force-dynamic';
export const metadata={title:'Terms · Bad Timing'};
export default function TermsPage(){const d=deploymentDetails();return <InfoLayout title="Terms" intro="A planning aid, not a promise that an event will be safe or uninterrupted.">
 <section className="info-section"><h2>The service</h2><p className="info-copy">BAD TIMING compares a place and time with selected public information. The service is operated by {d.operator||'the operator identified in the Privacy page when configured'}. It does not check private calendars, book venues, issue permits, reserve transport or establish anyone’s availability.</p></section>
 <section className="info-section"><h2>Understanding a report</h2><p className="info-copy">A report reflects only the connected sources, geographic scopes and records returned at the stated check time. Missing, stale, inaccessible, unconfigured or unsupported sources are not evidence that nothing is happening. Listings, timetables, warnings, road works and forecasts can change after a check.</p><p className="info-copy">“At this time” describes an overlap with a supplied or explicitly estimated time window. “Check locally” includes recent news, observations, incomplete schedules and regional context. A report may show multiple publishers describing the same situation. A selected radius is not an attendee’s travel route, a cordon or a hazard boundary.</p></section>
 <section className="info-section"><h2>Alternatives</h2><p className="info-copy">Suggestions use your Avoid / Doesn’t matter / Plan around choices and recheck a limited set of nearby candidate times. They are the best options among those checked, not a guaranteed global optimum. Live incidents, unknown end times and current warnings cannot be declared resolved merely because you move an event. “Plan around” is a soft timing preference, not a ticket, booking or verified attendance commitment.</p></section>
 <section className="info-section"><h2>Safety and official instructions</h2><p className="info-copy">Do not use this app as an emergency alerting system, evacuation tool, medical recommendation or substitute for official travel and safety instructions. A satellite hotspot is not a confirmed fire perimeter; an earthquake record is not a prediction; a news headline is not confirmation of a closure. Follow the issuing authority and venue, and use official emergency channels when needed.</p></section>
 <section className="info-section"><h2>Third-party information</h2><p className="info-copy">Source material remains subject to its publisher’s rights and data licence. A free API account does not grant unrestricted commercial use, redistribution or reuse of articles, photographs or databases. Preserve attribution and source links. Some datasets have share-alike or non-commercial conditions. The Sources page identifies the providers and applicable notices; their current terms prevail for their material.</p></section>
 <section className="info-section"><h2>Reasonable use</h2><p className="info-copy">Do not bypass rate limits, expose credentials, bulk-harvest the service, probe private network resources, upload unlawful material or use the app to track or target individuals. Check only information you are entitled to submit. Access may be limited to protect the service and upstream quotas.</p></section>
 <section className="info-section"><h2>Availability and responsibility</h2><p className="info-copy">The service may be interrupted or inaccurate, and its sources may become unavailable. Make your own arrangements and confirm material facts before inviting people or incurring costs. Nothing in these terms excludes rights or liability that cannot lawfully be excluded, or overrides mandatory consumer protections. These terms do not create an emergency-response obligation for the operator.</p></section>
 <section className="info-section"><h2>Privacy and contact</h2><p className="info-copy">The Privacy page describes what is sent, cached and logged. {d.contact?<>Questions or correction requests: <a href={`mailto:${d.contact}`}>{d.contact}</a>.</>:'The operator must publish its contact information before public launch.'}</p></section>
 <p className="info-footer">Terms version: {d.effective}. Operator-specific legal details and arrangements require review before a public launch.</p>
 </InfoLayout>;}
