import InfoLayout from '@/components/InfoLayout';
import {PROVIDERS} from '@/lib/connectors/catalog';
import {configuredFeeds,feedFamily} from '@/lib/connectors/feed-config';
export const dynamic='force-dynamic';
export const metadata={title:'Sources · Bad Timing'};
export default function SourcesPage(){
 const feeds=configuredFeeds().filter(f=>f.enabled);
 return <InfoLayout title="Sources" intro="What can be checked, what gets sent, and where the information comes from.">
  <section className="info-section"><h2>Coverage, not a guarantee</h2><p className="info-copy">A connection does not cover every place or future date. Each report shows which sources were actually checked. Regional feeds require a publisher, a mapped area and a valid data licence. A discovery catalogue is not an incident feed.</p></section>
  <section className="info-section"><h2>Data providers</h2><div className="provider-list">{PROVIDERS.map(p=>{
   const local=feeds.filter(f=>feedFamily(f)===p.id);
   const setup=p.mode==='feed'?(local.length?`${local.length} regional feed${local.length===1?'':'s'} configured`:'No regional feed configured'):p.mode==='discovery'?'Administrator discovery tool':p.mode==='key'?(p.env&&process.env[p.env]?'Credential configured · access checked per report':'Needs credentials'):'Runs when relevant';
   return <article className="provider-card" key={p.id} id={p.id}><div><h3>{p.name}</h3><p className="source-setup">{setup}</p><p>{p.coverage}</p></div><p><strong>Sent:</strong> {p.sends}</p><p><strong>Reuse:</strong> {p.licence}</p><div className="provider-links"><a href={p.docs} target="_blank" rel="noreferrer">Documentation ↗</a><a href={p.website} target="_blank" rel="noreferrer">Publisher ↗</a></div></article>;
  })}</div></section>
  <section className="info-section"><h2>Connected regional publishers</h2>{feeds.length?<div className="provider-list">{feeds.map(f=><article className="provider-card" key={f.id}><h3>{f.name}</h3><p>{f.attribution}</p><p>{f.countries.join(', ')} · {f.kind.toUpperCase()}</p><div className="provider-links"><a href={f.publicUrl} target="_blank" rel="noreferrer">Publisher ↗</a><a href={f.licenceUrl} target="_blank" rel="noreferrer">Data licence ↗</a></div></article>)}</div>:<p className="info-copy">No regional datasets have been connected on this deployment. The report will not imply they were checked.</p>}</section>
  <section className="info-section"><h2>Map and attribution</h2><div className="attribution-list"><span>Map data © <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>; location search by <a href="https://www.geoapify.com/terms-and-conditions/">Geoapify</a>.</span><span>Weather: MET Norway, <a href="https://docs.api.met.no/doc/License.html">CC BY 4.0</a>. Daylight: <a href="https://sunrise-sunset.org/">Sunrise-Sunset.org</a>.</span><span>TV data: <a href="https://www.tvmaze.com/api#licensing">TVmaze, CC BY-SA</a>. Holiday database: <a href="https://www.openholidaysapi.org/en/faq/">OpenHolidays, ODbL</a>.</span><span>Football data provided by the <a href="https://www.football-data.org/">football-data.org API</a>. Transit data: <a href="https://www.transit.land/terms">Transitland and its source agencies</a>.</span><span>Contains Transport for London data. Contains OS data © Crown copyright and database rights 2016. Geomni UK Map data © and database rights 2019.</span><span>Contains public sector information licensed under the <a href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/">Open Government Licence v3.0</a> where indicated by the publisher.</span><span>Additional records identify their own issuing agency or publisher. Their dataset terms apply independently.</span></div></section>
  <section className="info-section"><h2>Access and reuse</h2><p className="info-copy">Free access does not mean unrestricted reuse. Ticketmaster, Open-Meteo and Cloudflare Radar have commercial-use restrictions or plan requirements. Transit agencies and municipal datasets have their own licences. Source links are not endorsements. This app does not redistribute full news articles, subscriber content, photos or personal details from citizen reports.</p></section>
 </InfoLayout>;
}
